import Head from "next/head";
import GameoverScreen from "../components/GameoverScreen";
import Level from "../components/Level";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Not Flappy Bird</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-blue-400 h-screen relative">
        <Level />
        <GameoverScreen />
      </main>
    </div>
  );
}
